import type { Metadata } from "next";
import LegalPage, { type LegalSection } from "@/components/LegalPage";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: "How Streak X collects, uses, and protects personal information.",
};

const sections: LegalSection[] = [
  {
    id: "scope",
    title: "Scope",
    content: <><p>This Privacy Policy explains how Streak X collects, uses, stores, and shares information when you visit streakx.online, create an account, connect an X username, or use the Streak X service.</p><p>By using Streak X, you acknowledge the practices described here. If you do not agree with this policy, please do not use the service.</p></>,
  },
  {
    id: "information-we-collect",
    title: "Information we collect",
    content: <><p>We collect the information needed to operate your account and track your progress:</p><ul><li><strong>Account information:</strong> your email address, authentication identifiers, and account creation and sign-in records. Password authentication is handled by Supabase; Streak X does not store your plaintext password.</li><li><strong>Connected X information:</strong> the public X username and public account identifier you choose to connect.</li><li><strong>Goal and progress information:</strong> daily post and reply goals, public activity counts, goal completion, streak history, refresh usage, and synchronization timestamps.</li><li><strong>Preferences:</strong> your time zone and automatic-sync preference.</li><li><strong>Subscription information:</strong> your Creem customer, product, and subscription identifiers, billing interval, subscription status, and current access period. Streak X does not receive or store your full payment-card number.</li><li><strong>Technical information:</strong> essential session cookies and information ordinarily included in web requests, such as IP address, browser type, device type, and diagnostic records generated by our hosting and security providers.</li></ul></>,
  },
  {
    id: "sources",
    title: "Where information comes from",
    content: <><p>We receive information directly from you when you register, select goals, choose a time zone, or connect an X username. We retrieve public post and reply activity associated with that username through an X data provider. Creem sends us subscription events needed to grant, maintain, or remove paid access.</p><p>Streak X does not ask for or receive your X password and does not publish posts or replies on your behalf.</p></>,
  },
  {
    id: "how-we-use-data",
    title: "How we use information",
    content: <><p>We use information to authenticate users, provide the dashboard and activity heat map, calculate streaks, synchronize public X activity, apply local-day boundaries, manage subscriptions, prevent abuse, troubleshoot failures, communicate about accounts, and comply with legal obligations.</p><p>Where applicable law requires a legal basis, we process information to perform our contract with you, pursue legitimate interests in operating and securing Streak X, comply with law, and obtain consent where required.</p></>,
  },
  {
    id: "sharing",
    title: "How we share information",
    content: <><p>We disclose information only as needed to operate Streak X, complete transactions, protect the service, or comply with law. Current service providers include:</p><ul><li><strong>Supabase</strong> for authentication and database hosting.</li><li><strong>Vercel</strong> for application hosting and delivery.</li><li><strong>Creem</strong> as Merchant of Record for checkout, payments, taxes, subscription management, refunds, and chargebacks.</li><li><strong>Our SMTP email provider</strong> for confirmation, password-reset, and other transactional account emails.</li><li><strong>TwitterAPI.io and public X services</strong> for retrieving public account activity used by the tracking features.</li></ul><p>These providers process information under their own terms and privacy notices. We may also disclose information when required by law, to investigate misuse or security incidents, or as part of a merger, financing, acquisition, or sale of assets with appropriate protections.</p><p><strong>We do not sell personal information or share it for cross-context behavioral advertising.</strong></p></>,
  },
  {
    id: "cookies",
    title: "Cookies and local storage",
    content: <><p>Streak X uses essential cookies or similar browser storage to keep you signed in, protect authentication flows, remember your time zone, and maintain basic service operation. These technologies are required for the requested service.</p><p>We do not currently use third-party advertising cookies or behavioral advertising trackers. If this changes, we will update this policy and provide any controls required by law.</p></>,
  },
  {
    id: "retention",
    title: "Data retention",
    content: <><p>We retain account and progress information while your account remains active and as reasonably necessary to provide the service. Subscription and transaction-related records may be kept longer when required for accounting, fraud prevention, dispute handling, or legal compliance.</p><p>You may request account deletion by emailing support@streakx.online from your registered address. We may retain limited records where required by law or needed to establish, exercise, or defend legal claims. Backup copies may remain temporarily until normal backup cycles complete.</p></>,
  },
  {
    id: "security",
    title: "Security",
    content: <><p>We use reasonable administrative, technical, and organizational safeguards designed to protect personal information. These include authenticated access, restricted server credentials, database row-level access controls, and HTTPS in production.</p><p>No internet service can guarantee absolute security. You are responsible for using a strong, unique password and protecting access to your email account and devices.</p></>,
  },
  {
    id: "international",
    title: "International processing",
    content: <p>Streak X and its service providers may process information in countries other than your own. Those countries may have different data-protection laws. Where required, we and our providers use appropriate safeguards for international transfers.</p>,
  },
  {
    id: "rights",
    title: "Your choices and rights",
    content: <><p>Depending on your location, you may have rights to access, correct, delete, restrict, or object to processing of your personal information, or to receive a portable copy. You may update available account information in Settings, disconnect your X username, cancel your subscription through the Creem customer portal, or contact us with a privacy request.</p><p>We may ask you to verify your identity before completing a request. You may also have the right to complain to your local data-protection authority.</p></>,
  },
  {
    id: "children",
    title: "Children",
    content: <p>Streak X is not directed to children under 13, and paid subscriptions are intended for people legally able to enter a binding contract. We do not knowingly collect personal information from children under 13. Contact us if you believe a child has provided information so we can investigate and delete it where appropriate.</p>,
  },
  {
    id: "changes",
    title: "Changes to this policy",
    content: <p>We may update this policy as Streak X changes or legal requirements evolve. We will post the revised policy here and update its effective date. If a change materially affects how we use personal information, we will provide additional notice when reasonably required.</p>,
  },
  {
    id: "contact",
    title: "Contact",
    content: <p>For privacy questions or requests, contact Streak X at <a href="mailto:support@streakx.online">support@streakx.online</a>. Include “Privacy request” in the subject line and write from the email associated with your account when possible.</p>,
  },
];

export default function PrivacyPage() {
  return <LegalPage eyebrow="YOUR DATA. CLEARLY EXPLAINED." title="Privacy Policy" summary="What Streak X collects, why we need it, and the choices you have." effectiveDate="September 11, 2026" sections={sections} />;
}
